language: node_js
node_js:
  - "4"
before_install:
  - npm install
install:
  - chmod +x ./scripts/build.js
  - node ./scripts/build.js
deploy:
  - provider: elasticbeanstalk
    app: ajax.ripbin.com
    env: ajax-test-ripbin
    access_key_id: "AKIAIGEHZO373H6MTW6Q"
    secret_access_key: "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"
    region: us-west-2
    bucket_name: elasticbeanstalk-us-west-2-834835117621
    path: /ajax.ripbin.com
    zip_file: release-candidate.zip
    on:
      branch: test